name: civic_issue_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # CORE UPDATES
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.0
  
  # TOOLS
  http: ^1.2.1
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true